import { DocType } from '../../types/index.js';

export class DocGenerator {
  generate(type: DocType, data: Record<string, unknown>): string {
    switch (type) {
      case 'spec':
        return this.generateSpec(data);
      case 'decisions':
        return this.generateDecisions(data);
      case 'implementation':
        return this.generateImplementation(data);
      case 'test-plan':
        return this.generateTestPlan(data);
      case 'retrospective':
        return this.generateRetrospective(data);
      default:
        throw new Error(`Unknown doc type: ${type}`);
    }
  }

  private generateSpec(data: Record<string, unknown>): string {
    return `# Specification Document

## Project: ${data.projectName || 'Unknown'}

## Overview
${data.overview || 'TBD'}

## Requirements
${(data.requirements as string[])?.map(r => `- ${r}`).join('\n') || '- TBD'}

## Acceptance Criteria
- [ ] Criterion 1
- [ ] Criterion 2

*Generated by RQP v2.0.0*
`;
  }

  private generateDecisions(data: Record<string, unknown>): string {
    return `# Architecture Decision Records

## ADR-001: ${data.title || 'Decision'}

### Context
${data.context || 'TBD'}

### Decision
${data.decision || 'TBD'}

### Consequences
${(data.consequences as string[])?.map(c => `- ${c}`).join('\n') || '- TBD'}
`;
  }

  private generateImplementation(data: Record<string, unknown>): string {
    return `# Implementation Guide

## Setup
${data.setup || 'TBD'}

## Architecture
${data.architecture || 'TBD'}

## Key Components
- Component 1
- Component 2
`;
  }

  private generateTestPlan(data: Record<string, unknown>): string {
    return `# Test Plan

## Scope
${data.scope || 'TBD'}

## Test Cases
- [ ] Test Case 1
- [ ] Test Case 2

## Coverage Target
${data.coverage || '>80%'}
`;
  }

  private generateRetrospective(data: Record<string, unknown>): string {
    return `# Retrospective

## What Went Well
${(data.wentWell as string[])?.map(i => `- ${i}`).join('\n') || '- TBD'}

## What Could Improve
${(data.improvements as string[])?.map(i => `- ${i}`).join('\n') || '- TBD'}

## Action Items
- [ ] Action 1
- [ ] Action 2
`;
  }
}
